### ISSUE TITLE
pushing an application with the logger chart enabled kills fluentd

### ISSUE THREAD

**Issue by jchauncey** [deis/fluentd#10]
Steps to reproduce using the example-go app:

```
$ helm install deis-dev
$ helm install deis-logger
$ kubectl get pods --namespace=deis -o wide
$ deis register
$ deis keys:add
$ deis create foo
$ git push deis master
$ kubectl get pods --all-namespaces=true -o wide
```

One of the fluentd pods should be gone.

EDIT: Updated to reflect that it isnt always the same host that the app lives on

**Comment by krancour** [comment]
Is there a missing git push above?  I'm assuming merely creating the app does not trigger this.

**Comment by jchauncey** [comment]
yeah forgot to add that part thanks

**Comment by krancour** [comment]
I'll play with this.

**Comment by jchauncey** [comment]
being able to get successful deploys is making it really difficult to debug this issue

**Comment by jchauncey** [comment]
Ok I killed my old builder pod and got the new `v2-beta` image and now im not able to reproduce the error.

**Comment by jchauncey** [comment]
I'm closing this issue for now
