### ISSUE TITLE
Add ability to install/configure custom plugins.

### ISSUE THREAD

**Issue by mattk42** [deis/fluentd#39]
I had implemented a solution for this before the recent refactor, but then it was decided that just supporting the SumoLogic plugin natively would be a better solution.

But now I actually have the need to install a custom plugin I wrote to send some metric data to our own influxDB instance. The way to do this currently is building a completely custom fluentd docker image and using that. Would be nice if I could simply set some ENV vars and have the plugin installed/configured on startup.

I would propose doing this via a couple of ENV vars and a script that would handle the configuration/installation.

CUSTOM_PLUGIN_#=PLUGIN NAME
CUSTOM_OUTPUT_#=Block of text for custom output config.
CUSTOM_INPUT_#=Block of text for the custom input config.

I haven't re-implemented this yet, as I wanted to have the discussion on whether or not the project would be open to pulling in something like this before hand.

**Comment by jchauncey** [comment]
Yeah definitely lets see what it looks like and we can go from there

**Comment by mattk42** [comment]
@jchauncey Went ahead and put together #40 for this. Let me know what thoughts you have.

**Comment by jchauncey** [comment]
fixed in #43
