### ISSUE TITLE
Request for Gelf output plugin

### ISSUE THREAD

**Issue by mhulscher** [deis/fluentd#69]
I am hitting the syslog limit size of 1KB when using the syslog output handler in fluentd. I am sending my messages to graylog and would like to use Gelf to forward messages. There is a repository for a fluentd-gelf output plugin. However it is not in the gem repo. Any chance Deis can include this inside its fluentd?

https://github.com/emsearcy/fluent-plugin-gelf/tree/master/lib/fluent/plugin

**Comment by bacongobbler** [comment]
We would accept a PR to do so.
