### ISSUE TITLE
Grafana reports Fluentd memory leak

### ISSUE THREAD

**Issue by jayjun** [deis/fluentd#85]
- Deis v2.11.0
- Kubernetes v1.5.2

Just a week in production with one Deis app. Memory usage grew exponentially from 100 MB to around 380 MB. Interestingly only one pod leaks.

![fluentd](https://cloud.githubusercontent.com/assets/4433966/22930804/13d87eee-f2fd-11e6-9323-b96333e4ea64.png)

Very low volume site, and certainly no runaway logs from my app. However, [nsqd](https://github.com/deis/nsq) does log like a madman.

Created an issue so others may post similar findings.

**Comment by stuszynski** [comment]
Hi,

we encounter a similar issue.
![metric_explorer___datadog](https://cloud.githubusercontent.com/assets/1470018/22932371/f6c246a8-f2c7-11e6-8599-ab779427975a.jpg)

Environment:
- Deis v2.10.0
- Kubernetes v1.5.1
- remote syslog export outside of the cluster.

We decided to set a memory limit for fluentd but in fact, it just makes fluentd to be killed by OOM more frequently. Unfortunately, after that we encounter another issue. After each OOM kill of the Flutentd container there was a very high cpu/io spike (~50k iops) on the node. 

We didn't spot any suspicious activity near Flutentd containers or log pipeline, but we suspect that usage is growing much faster when Flutentd is logging non-ascii chars.

Our only solution so far, is a graceful restart of flunetd docker containers each night.

**Comment by jchauncey** [comment]
Trying to google around and see if there are any open issues against fluentd or the plugins we have installed that might be causing this problem but I am not having any luck.

**Comment by jchauncey** [comment]
@jayjun is the fluentd pod that is having the issues the same node that is also hosting nsq?

**Comment by jayjun** [comment]
@jchauncey Nope, nsqd is in my other node. Here are all the containers in the same node as the errant fluentd,

```
k8s_myapp-web.dc7b656d_myapp-web-3789995061-cm7lv
k8s_deis-builder.666551bb_deis-builder-805890417-50stb
k8s_deis-controller.8c80e6bd_deis-controller-3898609164-1z205
k8s_deis-logger-fluentd.85506d36_deis-logger-fluentd-cdblz
k8s_deis-logger-redis.fb946a63_deis-logger-redis-304849759-c8bkp
k8s_deis-logger.6b520480_deis-logger-176328999-hvzd2
k8s_deis-monitor-influxdb.43a7b400_deis-monitor-influxdb-2729657543-7vv4m
k8s_deis-monitor-telegraf.a4b3af_deis-monitor-telegraf-5hvvn
k8s_deis-registry-token-refresher.a5a2d75f_deis-registry-token-refresher-3889501108-dk1l3
k8s_deis-workflow-manager.b65ee28a_deis-workflow-manager-2528409207-x38fm
k8s_fluentd-cloud-logging.fe89ba10_fluentd-cloud-logging-gke-cluster-1-default-pool-0d4b1875-gf74
k8s_kube-proxy.9b4e199d_kube-proxy-gke-cluster-1-default-pool-0d4b1875-gf74
k8s_tiller.8f4765f0_tiller-deploy-3299276078-rvd9k
k8s_POD.d8dbe16c_myapp-web-3789995061-cm7lv
k8s_POD.d8dbe16c_deis-builder-805890417-50stb
k8s_POD.d8dbe16c_deis-controller-3898609164-1z205
k8s_POD.d8dbe16c_deis-logger-176328999-hvzd2
k8s_POD.d8dbe16c_deis-logger-fluentd-cdblz
k8s_POD.d8dbe16c_deis-logger-redis-304849759-c8bkp
k8s_POD.d8dbe16c_deis-monitor-influxdb-2729657543-7vv4m
k8s_POD.d8dbe16c_deis-monitor-telegraf-5hvvn
k8s_POD.d8dbe16c_deis-registry-token-refresher-3889501108-dk1l3
k8s_POD.d8dbe16c_deis-workflow-manager-2528409207-x38fm
k8s_POD.d8dbe16c_fluentd-cloud-logging-gke-cluster-1-default-pool-0d4b1875-gf74
k8s_POD.d8dbe16c_kube-proxy-gke-cluster-1-default-pool-0d4b1875-gf74
k8s_POD.d8dbe16c_tiller-deploy-3299276078-rvd9k
```

**Comment by jayjun** [comment]
Some updates. FYI, no one touched this cluster in the last 7 days.

### Fluentd

![fluentd](https://cloud.githubusercontent.com/assets/4433966/23191187/3fc88096-f8d7-11e6-978a-4b90d38eded9.jpg)

Memory leaks grow linearly for all Fluentd pods, not just one. `deis-logger-fluentd-cdblz` leaked 1 GB in 7 days!

My app was deployed on Feb 13, that's when slopes changed. So, it *is* somehow related to deployments.

### Others

I can't spot any correlation with other pods, except for [Workflow Manager](https://github.com/deis/workflow-manager). Not sure if they're related.

![workflow-manager](https://cloud.githubusercontent.com/assets/4433966/23191450/9adacd30-f8d8-11e6-81cc-76128d5be742.jpg)

Memory usage also [oddly] flatlined since 2 days ago.

---
I've gracefully restarted `deis-logger-fluentd-cdblz` today to see what happens.

**Comment by jayjun** [comment]
@mboersma There's a [memory fix](https://github.com/fluent/fluentd/blob/master/ChangeLog#L27) in Fluentd v0.14.13.

> * in_tail: Untracked files should be removed from watching list to avoid memory bloat
  https://github.com/fluent/fluentd/pull/1467

**Comment by mboersma** [comment]
> There's a [memory fix](https://github.com/fluent/fluentd/blob/master/ChangeLog#L27) in Fluentd v0.14.13.

Excellent, certainly worth a try. I'll go revise #87.

**Comment by mattk42** [comment]
Fyi, I have been running a pod with the fluentd upgrade for a bit. It has made a huge difference. 
![screenshot 2017-03-06 08 35 30](https://cloud.githubusercontent.com/assets/505046/23616880/6f2d3226-0248-11e7-8c30-9d31a15cf117.png)

**Comment by jchauncey** [comment]
Thats awesome @mattk42

**Comment by bacongobbler** [comment]
I think this can be closed now.
